apiVersion: v1
kind: Service
metadata:
  name: webflux-websocket
  namespace: wf-ws
spec:
  selector:
    app: webflux-websocket
  ports:
    - port: 8080
      name: http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webflux-websocket
  namespace: wf-ws
  labels:
    app: webflux-websocket
spec:
  replicas: 1
  template:
    metadata:
      name: webflux-websocket
      labels:
        app: webflux-websocket
    spec:
      containers:
        - name: webflux-websocket
          image: ersanmaz/webflux-websocket
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: webflux-websocket

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: webflux-websocket-gateway
  namespace: wf-ws
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webflux-websocket
  namespace: wf-ws
spec:
  hosts:
    - "*"
  gateways:
    - webflux-websocket-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: webflux-websocket
          weight: 100